services:
  bot:
    build: .
    image: blackbox:latest
    container_name: blackbox
    environment:
      TELEGRAM_RIO_BOT_TOKEN: ${TELEGRAM_RIO_BOT_TOKEN}
      TOMTOM_API_KEY: ${TOMTOM_API_KEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8100:8100"
